# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: releasebranch_8_4-ubuntu

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    container:
      image: osgeo/grass-gis:releasebranch_8_4-ubuntu
      options: --privileged

    steps:
    - uses: actions/checkout@v4

    - name: Install system deps
      run: |
        apt-get update
        apt-get install -y pandoc-citeproc qpdf

    - name: Install R
      run: |
        apt-get update
        apt-get install -y r-base

    - name: Download test dataset
      run: |
        wget https://grass.osgeo.org/sampledata/north_carolina/nc_basic_spm_grass7.zip -O /tmp/nc_basic_spm_grass7.zip
        unzip /tmp/nc_basic_spm_grass7.zip -d /tmp/grassdb

    - name: Install R dependencies
      run: |
        R -e "install.packages('remotes')"
        R -e "remotes::install_deps(dependencies = TRUE)"

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
        needs: check

    - uses: r-lib/actions/check-r-package@v2
      with:
        upload-snapshots: true
